### ISSUE TITLE
can't install wiringpi on raspy3

### ISSUE THREAD

**Issue by Trigun87** [eugeneware/wiring-pi#89]
when i try to install wiringpi it always fail

[https://pastebin.com/VJ4mS4MG](https://pastebin.com/VJ4mS4MG)

and  when i try to launch it 

>  sudo node remote.js
> module.js:557
>     throw err;
>     ^
> 
> Error: Cannot find module '../build/Release/wiringPi'
>     at Function.Module._resolveFilename (module.js:555:15)
>     at Function.Module._load (module.js:482:25)
>     at Module.require (module.js:604:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/home/pi/node_modules/wiring-pi/lib/exports.js:1:80)
>     at Module._compile (module.js:660:30)
>     at Object.Module._extensions..js (module.js:671:10)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)

how i can solve it?

**Comment by ManfredSteiner** [comment]
I had similar problems on my Raspberry Pi 2 Model B v1.1. After switching back to kernel 4.4 (using command `rpi-update 52241088c1da59a359110d39c1875cda56496764`) and switching to Node.js v8.9.4 it could be installed and it was working. 

Installing [wiringpi-node](https://www.npmjs.com/package/wiringpi-node) instead of [wiring-pi](https://www.npmjs.com/package/wiring-pi) was also working on kernel 4.14.20-v7+ (using command `rpi-update` to update kernel to latest version).

That's not a solution, but maybe it helps...

**Comment by AckerApple** [comment]
Thank you @ManfredSteiner

Could not get pi3 to run using wiring-pi. Switch my require to wiringpi-node and all is working now.

Awesome

**Comment by davidck** [comment]
On 3 model b+, wiringpi-node works for me also.  Was getting this error:
```
Unable to determine hardware version. I see: Hardware	: BCM2835
,
 - expecting BCM2708 or BCM2709. Please report this to projects@drogon.net
```
